### ISSUE TITLE
Need update for 2024 season

### ISSUE THREAD

**Issue by gk-brown** [REVrobotics/SPARK-MAX-Examples#33]
Apparently the 2024 version of wpilib requires a "year" declaration in the vendordeps configuration. Without this, the build produces the following error:

> Vendor Dependency REVRobotics has invalid year null. Expected to be 2024.

I was able to work around this by manually adding the following to `vendordeps/REVRobotics.json` and refreshing the dependency:

```json
"frcYear": "2024"
```

I added it immediately following the "uuid" value, mirroring the structure of the 2024 `WPILibNewCommands.json` file.

**Comment by gk-brown** [comment]
Apparently this change is not sufficient - even though I no longer get the "null year" error, I am unable to reference any `com.revrobotics` classes. It seems like the dependency is not being pulled in correctly.

**Comment by jfabellera** [comment]
The vendordep json used for the examples have not yet been updated for 2024 season. The latest version of REVLib is available [here](https://github.com/REVrobotics/REV-Software-Binaries/releases/tag/revlib-2024.2.0).

**Comment by jfabellera** [comment]
It looks like the README of this repo is out of date for installing REVLib as well, that may explain why you have a `REVRobotics.json` instead of a `REVLib.json`.

Please follow the [instructions from WPILib for installing 3rd party libraries](https://docs.wpilib.org/en/stable/docs/software/vscode-overview/3rd-party-libraries.html) and use the vendordep URL in the release linked above.

**Comment by gk-brown** [comment]
@jfabellera Thank you, I will give that a try.

**Comment by gk-brown** [comment]
Closing since this issue will be resolved by #34.
